=== rvsharma-cmu/CloudFormationModules/env/lib/python3.7/site-packages/rpdk/core/data/schema/provider.definition.schema.modules.v1.json
{
    "$schema": "https://json-schema.org/draft-07/schema#",
    "$id": "https://schema.cloudformation.us-east-1.amazonaws.com/module.definition.schema.v1.json",
    "title": "CloudFormation Module Provider Definition MetaSchema",
    "description": "This schema validates a CloudFormation module provider definition.",
    "definitions": {
        "httpsUrl": {
            "type": "string",
            "pattern": "^https://[0-9a-zA-Z]([-.\\w]*[0-9a-zA-Z])(:[0-9]*)*([?/#].*)?$",
            "maxLength": 4096
        },
        "handlerDefinition": {
            "description": "Defines any execution operations which can be performed on this module provider",
            "type": "object",
            "properties": {
                "permissions": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "additionalItems": false
                },
                "timeoutInMinutes": {
                    "description": "Defines the timeout for the entire operation to be interpreted by the invoker of the handler.  The default is 120 (2 hours).",
                    "type": "integer",
                    "minimum": 2,
                    "maximum": 720,
                    "default": 120
                }
            },
            "additionalProperties": false,
            "required": [
                "permissions"
            ]
        },
        "jsonPointerArray": {
            "type": "array",
            "minItems": 1,
            "items": {
                "type": "string",
                "format": "json-pointer"
            }
        },
        "schemaArray": {
            "type": "array",
            "minItems": 1,
            "items": {
                "$ref": "#/definitions/properties"
            }
        },
        "validations": {
            "dependencies": {
                "enum": {
                    "$comment": "Enforce that properties are strongly typed when enum, or const is specified.",
                    "required": [
                        "type"
                    ]
                },
                "const": {
                    "required": [
                        "type"
                    ]
                },
                "properties": {
                    "$comment": "An object cannot have both defined and undefined properties; therefore, patternProperties is not allowed when properties is specified.",
                    "not": {
                        "required": [
                            "patternProperties"
                        ]
                    }
                }
            }
        },
        "replacementStrategy": {
            "type": "string",
            "description": "The valid replacement strategies are [create_then_delete] and [delete_then_create]. All other inputs are invalid.",
            "default": [
                "create_then_delete"
            ],
            "enum": [
                "create_then_delete",
                "delete_then_create"
            ]
        },
        "properties": {
            "allOf": [
                {
                    "$ref": "#/definitions/validations"
                },
                {
                    "$comment": "The following subset of draft-07 property references is supported for module definitions. Nested properties are disallowed and should be specified as a $ref to a definitions block.",
                    "type": "object",
                    "properties": {
                        "insertionOrder": {
                            "description": "When set to true, this flag indicates that the order of insertion of the array will be honored, and that changing the order of the array would indicate a diff",
                            "type": "boolean",
                            "default": true
                        },
                        "$ref": {
                            "$ref": "https://json-schema.org/draft-07/schema#/properties/$ref"
                        },
                        "$comment": {
                            "$ref": "https://json-schema.org/draft-07/schema#/properties/$comment"
                        },
                        "title": {
                            "$ref": "https://json-schema.org/draft-07/schema#/properties/title"
                        },
                        "description": {
                            "$ref": "https://json-schema.org/draft-07/schema#/properties/description"
                        },
                        "examples": {
                            "$ref": "https://json-schema.org/draft-07/schema#/properties/examples"
                        },
                        "default": {
                            "$ref": "https://json-schema.org/draft-07/schema#/properties/default"
                        },
                        "multipleOf": {
                            "$ref": "https://json-schema.org/draft-07/schema#/properties/multipleOf"
                        },
                        "maximum": {
                            "$ref": "https://json-schema.org/draft-07/schema#/properties/maximum"
                        },
                        "exclusiveMaximum": {
                            "$ref": "https://json-schema.org/draft-07/schema#/properties/exclusiveMaximum"
                        },
                        "minimum": {
                            "$ref": "https://json-schema.org/draft-07/schema#/properties/minimum"
                        },
                        "exclusiveMinimum": {
                            "$ref": "https://json-schema.org/draft-07/schema#/properties/exclusiveMinimum"
                        },
                        "maxLength": {
                            "$ref": "https://json-schema.org/draft-07/schema#/properties/maxLength"
                        },
                        "minLength": {
                            "$ref": "https://json-schema.org/draft-07/schema#/properties/minLength"
                        },
                        "pattern": {
                            "$ref": "https://json-schema.org/draft-07/schema#/properties/pattern"
                        },
                        "items": {
                            "$comment": "Redefined as just a schema. A list of schemas is not allowed",
                            "$ref": "#/definitions/properties",
                            "default": {}
                        },
                        "maxItems": {
                            "$ref": "https://json-schema.org/draft-07/schema#/properties/maxItems"
                        },
                        "minItems": {
                            "$ref": "https://json-schema.org/draft-07/schema#/properties/minItems"
                        },
                        "uniqueItems": {
                            "$ref": "https://json-schema.org/draft-07/schema#/properties/uniqueItems"
                        },
                        "contains": {
                            "$ref": "https://json-schema.org/draft-07/schema#/properties/contains"
                        },
                        "maxProperties": {
                            "$ref": "https://json-schema.org/draft-07/schema#/properties/maxProperties"
                        },
                        "minProperties": {
                            "$ref": "https://json-schema.org/draft-07/schema#/properties/minProperties"
                        },
                        "required": {
                            "$ref": "https://json-schema.org/draft-07/schema#/properties/required"
                        },
                        "properties": {
                            "type": "object",
                            "patternProperties": {
                                "^[A-Za-z0-9]{1,64}$": {
                                    "$ref": "#/definitions/properties"
                                }
                            },
                            "additionalProperties": false,
                            "minProperties": 1
                        },
                        "additionalProperties": {
                            "$comment": "All properties of a resource must be expressed in the schema - arbitrary inputs are not allowed",
                            "type": "boolean"
                        },
                        "patternProperties": {
                            "$comment": "patternProperties allow providers to introduce a specification for key-value pairs, or Map inputs.",
                            "type": "object",
                            "propertyNames": {
                                "format": "regex"
                            }
                        },
                        "dependencies": {
                            "$comment": "Redefined to capture our properties override.",
                            "type": "object",
                            "additionalProperties": {
                                "anyOf": [
                                    {
                                        "$ref": "#/definitions/properties"
                                    },
                                    {
                                        "$ref": "https://json-schema.org/draft-07/schema#/definitions/stringArray"
                                    }
                                ]
                            }
                        },
                        "const": {
                            "$ref": "https://json-schema.org/draft-07/schema#/properties/const"
                        },
                        "enum": {
                            "$ref": "https://json-schema.org/draft-07/schema#/properties/enum"
                        },
                        "type": {
                            "$ref": "https://json-schema.org/draft-07/schema#/properties/type"
                        },
                        "format": {
                            "$ref": "https://json-schema.org/draft-07/schema#/properties/format"
                        },
                        "allOf": {
                            "$ref": "#/definitions/schemaArray"
                        },
                        "anyOf": {
                            "$ref": "#/definitions/schemaArray"
                        },
                        "oneOf": {
                            "$ref": "#/definitions/schemaArray"
                        },
                        "Resources": {
                            "description": "List of all the resources that module creates.",
                            "type": "object"
                        },
                        "Parameters": {
                            "description": "List of input parameters",
                            "type": "object"
                        }
                    },
                    "additionalProperties": false
                }
            ]
        },
        "moduleLink": {
            "type": "object",
            "properties": {
                "$comment": {
                    "$ref": "https://json-schema.org/draft-07/schema#/properties/$comment"
                },
                "templateUri": {
                    "type": "string",
                    "pattern": "^(/|https:)"
                },
                "mappings": {
                    "type": "object",
                    "patternProperties": {
                        "^[A-Za-z0-9]{1,64}$": {
                            "type": "string",
                            "format": "json-pointer"
                        }
                    },
                    "additionalProperties": false
                }
            },
            "required": [
                "templateUri",
                "mappings"
            ],
            "additionalProperties": false
        }
    },
    "type": "object",
    "patternProperties": {
        "^\\$id$": {
            "$ref": "https://json-schema.org/draft-07/schema#/properties/$id"
        }
    },
    "properties": {
        "$schema": {
            "$ref": "https://json-schema.org/draft-07/schema#/properties/$schema"
        },
        "type": {
            "$comment": "Type",
            "type": "string",
            "const": "MODULE"
        },
        "typeName": {
            "$comment": "Module Type Identifier",
            "examples": [
                "Organization::Service::XYZ::MODULE",
                "AWS::S3::SecureBucket::MODULE"
            ],
            "type": "string",
            "pattern": "^[a-zA-Z0-9]{2,64}::[a-zA-Z0-9]{2,64}::[a-zA-Z0-9]{2,64}::MODULE$"
        },
        "$comment": {
            "$ref": "https://json-schema.org/draft-07/schema#/properties/$comment"
        },
        "title": {
            "$ref": "https://json-schema.org/draft-07/schema#/properties/title"
        },
        "description": {
            "$comment": "A short description of the module provider. This will be shown in the AWS CloudFormation console.",
            "$ref": "https://json-schema.org/draft-07/schema#/properties/description"
        },
        "sourceUrl": {
            "$comment": "The location of the source code for this module provider, to help interested parties submit issues or improvements.",
            "examples": [
                "https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-s3"
            ],
            "$ref": "#/definitions/httpsUrl"
        },
        "documentationUrl": {
            "$comment": "A page with supplemental documentation. The property documentation in schemas should be able to stand alone, but this is an opportunity for e.g. rich examples or more guided documents.",
            "examples": [
                "https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/CHAP_Using.html"
            ],
            "$ref": "#/definitions/httpsUrl"
        },
        "additionalProperties": {
            "$comment": "Does schema allow additional properties for a some types",
            "type": "boolean"
        },
        "properties": {
            "type": "object",
            "patternProperties": {
                "^[A-Za-z0-9]{1,64}$": {
                    "$ref": "#/definitions/properties"
                }
            },
            "additionalProperties": true,
            "minProperties": 1,
            "required": ["Resources"]
        },
        "definitions": {
            "type": "object",
            "patternProperties": {
                "^[A-Za-z0-9]{1,64}$": {
                    "$ref": "#/definitions/properties"
                }
            },
            "additionalProperties": false
        },
        "handlers": {
            "description": "Defines the provisioning operations which can be performed on this type",
            "type": "object",
            "properties": {
                "resolve": {
                    "$ref": "#/definitions/handlerDefinition"
                }
            },
            "additionalProperties": false
        },
        "remote": {
            "description": "Reserved for CloudFormation use. A namespace to inline remote schemas.",
            "type": "object",
            "patternProperties": {
                "^schema[0-9]+$": {
                    "description": "Reserved for CloudFormation use. A inlined remote schema.",
                    "type": "object",
                    "properties": {
                        "$comment": {
                            "$ref": "https://json-schema.org/draft-07/schema#/properties/$comment"
                        },
                        "properties": {
                            "$ref": "#/properties/properties"
                        },
                        "definitions": {
                            "$ref": "#/properties/definitions"
                        }
                    },
                    "additionalProperties": true
                }
            },
            "additionalProperties": false
        },
        "replacementStrategy": {
            "$comment": "The order of replacement for an immutable module update.",
            "$ref": "#/definitions/replacementStrategy"
        },
        "required": {
            "$ref": "https://json-schema.org/draft-07/schema#/properties/required"
        },
        "allOf": {
            "$ref": "#/definitions/schemaArray"
        },
        "anyOf": {
            "$ref": "#/definitions/schemaArray"
        },
        "oneOf": {
            "$ref": "#/definitions/schemaArray"
        },
        "moduleLink": {
            "description": "A template-able link to a resource instance. AWS-internal service links must be relative to the AWS console domain. External service links must be absolute, HTTPS URIs.",
            "$ref": "#/definitions/moduleLink"
        }
    },
    "required": [
        "typeName",
        "properties",
        "description",
        "additionalProperties"
    ],
    "additionalProperties": false
}

=== rvsharma-cmu/CloudFormationModules/schema.json
{
    "typeName": "MyCompany::S3::Bucket::MODULE",
    "description": "Schema for Module Fragment of type MyCompany::S3::Bucket::MODULE",
    "properties": {
        "Parameters": {
            "type": "object",
            "properties": {
                "KMSKeyAlias": {
                    "type": "object",
                    "properties": {
                        "Type": {
                            "type": "string"
                        },
                        "Description": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "Type",
                        "Description"
                    ],
                    "description": "The alias for your KMS key. If you will leave this field empty KMS key alias won't be created along the key."
                },
                "ReadOnlyArn": {
                    "type": "object",
                    "properties": {
                        "Type": {
                            "type": "string"
                        },
                        "Description": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "Type",
                        "Description"
                    ],
                    "description": "Provide ARN of an existing Principal (role) that will be granted with read only access to the S3 bucket (e.g. 'arn:aws:iam::123456789xxx:role/myS3ROrole'). If not specified, access will be granted to current AWS account:root only. CF deployment will fail and rollback for non-existing ARN."
                },
                "ReadWriteArn": {
                    "type": "object",
                    "properties": {
                        "Type": {
                            "type": "string"
                        },
                        "Description": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "Type",
                        "Description"
                    ],
                    "description": "Provide ARN of an existing Principal (role) that will be granted with read and write access to the S3 bucket (e.g. 'arn:aws:iam::123456789xxx:role/myS3RWrole'). If not specified, access will be granted to current AWS account:root only. CF deployment will fail and rollback for non-existing ARN."
                }
            }
        },
        "Resources": {
            "properties": {
                "KmsKey": {
                    "type": "object",
                    "properties": {
                        "Type": {
                            "type": "string",
                            "const": "AWS::KMS::Key"
                        },
                        "Properties": {
                            "type": "object"
                        }
                    }
                },
                "KmsKeyAlias": {
                    "type": "object",
                    "properties": {
                        "Type": {
                            "type": "string",
                            "const": "AWS::KMS::Alias"
                        },
                        "Properties": {
                            "type": "object"
                        }
                    }
                },
                "Bucket": {
                    "type": "object",
                    "properties": {
                        "Type": {
                            "type": "string",
                            "const": "AWS::S3::Bucket"
                        },
                        "Properties": {
                            "type": "object"
                        }
                    }
                },
                "BucketPolicy": {
                    "type": "object",
                    "properties": {
                        "Type": {
                            "type": "string",
                            "const": "AWS::S3::BucketPolicy"
                        },
                        "Properties": {
                            "type": "object"
                        }
                    }
                }
            },
            "type": "object",
            "additionalProperties": false
        }
    },
    "additionalProperties": true
}
